### ISSUE TITLE
工具类第一期]特征图可视化.ipynb

### ISSUE THREAD

**Issue by najingligong1111** [open-mmlab/OpenMMLabCourse#35]
Unreadable Notebook: /home/mingkd/mmyolo/[工具类第一期]特征图可视化.ipynb NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html la...")

**Comment by wangruohui** [comment]
Hi @RangeKing, this seems to be uploaded from you, could you help to solve this issue?

**Comment by RangeKing** [comment]
I open this notebook by colab and vscode without any error.
